version: "3.7"

services:
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: exampledb
    container_name: flyway-callback-java-db
